options:
  logging: CLOUD_LOGGING_ONLY

serviceAccount: 358360597696@cloudbuild.gserviceaccount.com
steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-east1-docker.pkg.dev/jrosadob-ms-project/docker/auth-ms",
        "-f",
        "Dockerfile.prod",
        "--platform=linux/amd64",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-east1-docker.pkg.dev/jrosadob-ms-project/docker/auth-ms",
      ]