version: '3.9'

services:
  nats-server:
    image: nats:latest

  ms-auth:
    build:
      context: .
      dockerfile: Dockerfile.develop
    image: ms-auth
    volumes:
      - ./src:/usr/src
    command: npm run start:dev
    environment:
      - PORT=3004
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${AUTH_DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - "8222:8222"
